pipelines:
  default:
    - step:
        image: theese/laravel-dusk
        caches:
          - node
          - composer
          - vendor
        script:
          # Setup MySQL
          - service mysql start
          - mysql -h localhost --user=laravel --password=secret -e "CREATE DATABASE simplo_cms_testing;"
          # Setup Apache2
          - ln -s $BITBUCKET_CLONE_DIR /var/www/laravel
          - echo '127.0.0.1 laravel.test' >> /etc/hosts
          - service apache2 start
          # Build frontend
          - npm install
          - npm run prod
          # Setup CMS
          - printf '%s\n' 'APP_ENV=testing' 'APP_DEBUG=false' 'DB_CONNECTION=testing' 'DB_HOST=localhost' 'DB_PORT=3306' 'DB_DATABASE=simplo_cms_testing' 'DB_USERNAME=laravel' 'DB_PASSWORD=secret' 'TESTING_DB_DATABASE=simplo_cms_testing' 'APP_KEY=' 'APP_URL=http://laravel.test' 'CACHE_DRIVER=array' 'DUSK_START_BROWSER_MANUALLY=true' 'DEFAULT_LOCALE=en' 'ENABLED_LOCALES=cs,en' > .env
          - composer update
          - php artisan key:generate
          - php artisan migrate
          - chgrp -R www-data storage bootstrap/cache public
          - chmod -R ug+rwx storage bootstrap/cache public
          # Run tests
          - chmod +x vendor/laravel/dusk/bin/chromedriver-linux
          - vendor/laravel/dusk/bin/chromedriver-linux &
          - php artisan run-tests --log-junit ./test-reports/result.xml
        artifacts:
          - tests/Browser/screenshots/*.png
          - storage/logs/laravel.log

definitions:
    caches:
        vendor: vendor
