version: '2'
services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: simplo-cms
    ports:
      - 8180:80
      - 9000
    volumes:
      - .:/srv/simplo-cms
    links:
      - dbm
    environment:
      APP_URL: http://localhost:8180
      DB_HOST: dbm
      DB_CONNECTION: mysql
      TESTING_DB_DATABASE: simplo_cms_testing
      DB_DATABASE: cms
      DB_USERNAME: root
      DB_PASSWORD: secret
      SESSION_DRIVER: file
      CACHE_DRIVER: file
      XDEBUG_CONFIG: remote_host=172.18.0.1
  dbm:
      image: mysql:5.6
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: cms
        MYSQL_USER: cms
        MYSQL_PASSWORD: secret
  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080
